//! The renderers: each writes one kind of generated file from the [`Model`].

pub mod accessors;
pub mod redaction;
pub mod routes;
pub mod services;
pub mod types;

use std::fmt::Write;

use crate::model::{Model, Operation};

/// The first line of every generated file.
pub const HEADER: &str = "// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.\n\n";

/// A rustdoc comment from a block of text, one `///` per line.
pub fn doc_comment(text: &str, indent: &str) -> String {
    text.lines()
        .map(|line| {
            if line.trim().is_empty() {
                format!("{indent}///\n")
            } else {
                format!("{indent}/// {}\n", line.trim_end())
            }
        })
        .collect()
}

/// What an operation's rustdoc says. The model carries no prose, so the doc is the facts
/// the behavior model does carry: the request line, and how the client treats the call.
pub fn operation_doc(operation: &Operation) -> String {
    let mut doc = format!(
        "`{}` — `{} {}`.\n\n",
        operation.id, operation.http_method, operation.path
    );
    match &operation.retry {
        Some(retry) => {
            let statuses: Vec<String> = retry.retry_on.iter().map(u16::to_string).collect();
            let _ = write!(
                doc,
                "Sent up to {} times, backing off from {} ms, when the answer is {}.",
                retry.max,
                retry.base_delay_ms,
                join_or(&statuses)
            );
        }
        None => doc.push_str("Sent once and never resent."),
    }
    if operation.idempotent && operation.http_method == "POST" {
        doc.push_str(" Idempotent, so a resend is safe.");
    }
    if let Some(page_param) = &operation.page_param {
        let _ = write!(
            doc,
            "\n\nPaginated: the answer is a page with `{page_param}` as its cursor, and the next one is read with `next_page`."
        );
    }
    doc
}

fn join_or(items: &[String]) -> String {
    match items {
        [] => String::new(),
        [only] => only.clone(),
        [rest @ .., last] => format!("{} or {last}", rest.join(", ")),
    }
}

/// The `mod.rs` at the top of the generated tree.
pub fn render_mod(model: &Model) -> String {
    format!(
        "{HEADER}#![allow(clippy::pedantic, unreachable_pub)]\n\npub mod accessors;\npub mod redaction;\npub mod routes;\npub mod services;\npub mod types;\n\n/// The Fizzy API version this SDK was generated against.\npub const API_VERSION: &str = \"{}\";\n",
        model.api_version
    )
}
