// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateAccessToken`.
#[tokio::test]
async fn create() {
    let server = MockServer::start().await;
    let expected: AccessToken = Default::default();
    let body = CreateAccessTokenRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/my/access_tokens.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server).access_tokens().create(&body).await.unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeleteAccessToken`.
#[tokio::test]
async fn delete() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/my/access_tokens/x-access_token_id"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .access_tokens()
        .delete("x-access_token_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `ListAccessTokens`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<AccessToken> = Default::default();
    Mock::given(method("GET"))
        .and(path("/my/access_tokens.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server).access_tokens().list().await.unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}
