// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateAccountExport`.
#[tokio::test]
async fn create_export() {
    let server = MockServer::start().await;
    let expected: AccountExport = Default::default();
    Mock::given(method("POST"))
        .and(path("/999/account/exports.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .account()
        .create_export()
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `GetAccountExport`.
#[tokio::test]
async fn get_export() {
    let server = MockServer::start().await;
    let expected: AccountExport = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/account/exports/x-export_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .account()
        .get_export("x-export_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `GetJoinCode`.
#[tokio::test]
async fn get_join_code() {
    let server = MockServer::start().await;
    let expected: JoinCode = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/account/join_code.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .account()
        .get_join_code()
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `GetAccountSettings`.
#[tokio::test]
async fn get_settings() {
    let server = MockServer::start().await;
    let expected: AccountSettings = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/account/settings.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .account()
        .get_settings()
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ResetJoinCode`.
#[tokio::test]
async fn reset_join_code() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/account/join_code.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .account()
        .reset_join_code()
        .await
        .unwrap();
    server.verify().await;
}

/// `UpdateAccountEntropy`.
#[tokio::test]
async fn update_entropy() {
    let server = MockServer::start().await;
    let expected: AccountSettings = Default::default();
    let body = UpdateAccountEntropyRequestContent::default();
    Mock::given(method("PUT"))
        .and(path("/999/account/entropy.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .account()
        .update_entropy(&body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `UpdateJoinCode`.
#[tokio::test]
async fn update_join_code() {
    let server = MockServer::start().await;
    let body = UpdateJoinCodeRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/account/join_code.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .account()
        .update_join_code(&body)
        .await
        .unwrap();
    server.verify().await;
}

/// `UpdateAccountSettings`.
#[tokio::test]
async fn update_settings() {
    let server = MockServer::start().await;
    let body = UpdateAccountSettingsRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/account/settings.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .account()
        .update_settings(&body)
        .await
        .unwrap();
    server.verify().await;
}
