// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use fizzy_sdk::services::boards::*;
use wiremock::matchers::{body_json, method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateBoard`.
#[tokio::test]
async fn create() {
    let server = MockServer::start().await;
    let expected: Board = Default::default();
    let body = CreateBoardRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/boards.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .create(&body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeleteBoard`.
#[tokio::test]
async fn delete() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/boards/x-board_id"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .delete("x-board_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `GetBoard`.
#[tokio::test]
async fn get() {
    let server = MockServer::start().await;
    let expected: Board = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .get("x-board_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListBoards`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Board> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .list()
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `ListBoardAccesses`.
#[tokio::test]
async fn list_board_accesses() {
    let server = MockServer::start().await;
    let expected: BoardAccesses = Default::default();
    let params = ListBoardAccessesParams { page: Some(7) };
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id/accesses.json"))
        .and(query_param("page", "7"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .list_board_accesses("x-board_id", &params)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListClosedCards`.
#[tokio::test]
async fn list_closed() {
    let server = MockServer::start().await;
    let expected: Vec<Card> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id/columns/closed.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .list_closed("x-board_id")
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `ListPostponedCards`.
#[tokio::test]
async fn list_postponed() {
    let server = MockServer::start().await;
    let expected: Vec<Card> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id/columns/not_now.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .list_postponed("x-board_id")
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `ListStreamCards`.
#[tokio::test]
async fn list_stream() {
    let server = MockServer::start().await;
    let expected: Vec<Card> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id/columns/stream.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .list_stream("x-board_id")
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `PublishBoard`.
#[tokio::test]
async fn publish() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/boards/x-board_id/publication.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .publish("x-board_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `UnpublishBoard`.
#[tokio::test]
async fn unpublish() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/boards/x-board_id/publication.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .unpublish("x-board_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `UpdateBoard`.
#[tokio::test]
async fn update() {
    let server = MockServer::start().await;
    let expected: Board = Default::default();
    let body = UpdateBoardRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/boards/x-board_id"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .update("x-board_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `UpdateBoardEntropy`.
#[tokio::test]
async fn update_entropy() {
    let server = MockServer::start().await;
    let expected: Board = Default::default();
    let body = UpdateBoardEntropyRequestContent::default();
    Mock::given(method("PUT"))
        .and(path("/999/boards/x-board_id/entropy.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .update_entropy("x-board_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `UpdateBoardInvolvement`.
#[tokio::test]
async fn update_involvement() {
    let server = MockServer::start().await;
    let body = UpdateBoardInvolvementRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/boards/x-board_id/involvement.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .boards()
        .update_involvement("x-board_id", &body)
        .await
        .unwrap();
    server.verify().await;
}
