// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use fizzy_sdk::services::cards::*;
use wiremock::matchers::{body_json, method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `AssignCard`.
#[tokio::test]
async fn assign() {
    let server = MockServer::start().await;
    let body = AssignCardRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/cards/7/assignments.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .assign(7, &body)
        .await
        .unwrap();
    server.verify().await;
}

/// `CloseCard`.
#[tokio::test]
async fn close() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/cards/7/closure.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .close(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `CreateCard`.
#[tokio::test]
async fn create() {
    let server = MockServer::start().await;
    let expected: Card = Default::default();
    let body = CreateCardRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/cards.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .create(&body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeleteCard`.
#[tokio::test]
async fn delete() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .delete(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `DeleteCardImage`.
#[tokio::test]
async fn delete_image() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/image.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .delete_image(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `GetCard`.
#[tokio::test]
async fn get() {
    let server = MockServer::start().await;
    let expected: Card = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/cards/7"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .get(7)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `GoldCard`.
#[tokio::test]
async fn gold() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/cards/7/goldness.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .gold(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `ListCards`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Card> = Default::default();
    let params = ListCardsParams {
        board_ids: Some(vec!["x".into()]),
        tag_ids: Some(vec!["x".into()]),
        assignee_ids: Some(vec!["x".into()]),
        creator_ids: Some(vec!["x".into()]),
        closer_ids: Some(vec!["x".into()]),
        card_ids: Some(vec!["x".into()]),
        column_ids: Some(vec!["x".into()]),
        indexed_by: Some("x".into()),
        sorted_by: Some("x".into()),
        assignment_status: Some("x".into()),
        creation: Some("x".into()),
        closure: Some("x".into()),
        terms: Some(vec!["x".into()]),
    };
    Mock::given(method("GET"))
        .and(path("/999/cards.json"))
        .and(query_param("board_ids[]", "x"))
        .and(query_param("tag_ids[]", "x"))
        .and(query_param("assignee_ids[]", "x"))
        .and(query_param("creator_ids[]", "x"))
        .and(query_param("closer_ids[]", "x"))
        .and(query_param("card_ids[]", "x"))
        .and(query_param("column_ids[]", "x"))
        .and(query_param("indexed_by", "x"))
        .and(query_param("sorted_by", "x"))
        .and(query_param("assignment_status", "x"))
        .and(query_param("creation", "x"))
        .and(query_param("closure", "x"))
        .and(query_param("terms[]", "x"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .list(&params)
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `ListActivities`.
#[tokio::test]
async fn list_activities() {
    let server = MockServer::start().await;
    let expected: Vec<Activity> = Default::default();
    let params = ListActivitiesParams {
        creator_ids: Some(vec!["x".into()]),
        board_ids: Some(vec!["x".into()]),
    };
    Mock::given(method("GET"))
        .and(path("/999/activities.json"))
        .and(query_param("creator_ids[]", "x"))
        .and(query_param("board_ids[]", "x"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .list_activities(&params)
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `ListColumnCards`.
#[tokio::test]
async fn list_column_cards() {
    let server = MockServer::start().await;
    let expected: Vec<Card> = Default::default();
    Mock::given(method("GET"))
        .and(path(
            "/999/boards/x-board_id/columns/x-column_id/cards.json",
        ))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .list_column_cards("x-board_id", "x-column_id")
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `MarkCardRead`.
#[tokio::test]
async fn mark_read() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/cards/7/reading.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .mark_read(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `MarkCardUnread`.
#[tokio::test]
async fn mark_unread() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/reading.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .mark_unread(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `MoveCard`.
#[tokio::test]
async fn move_to_board() {
    let server = MockServer::start().await;
    let expected: Card = Default::default();
    let body = MoveCardRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/cards/7/board.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .move_to_board(7, &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `PinCard`.
#[tokio::test]
async fn pin() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/cards/7/pin.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .pin(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `PostponeCard`.
#[tokio::test]
async fn postpone() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/cards/7/not_now.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .postpone(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `PublishCard`.
#[tokio::test]
async fn publish() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/cards/7/publish.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .publish(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `ReopenCard`.
#[tokio::test]
async fn reopen() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/closure.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .reopen(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `SelfAssignCard`.
#[tokio::test]
async fn self_assign() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/cards/7/self_assignment.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .self_assign(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `TagCard`.
#[tokio::test]
async fn tag() {
    let server = MockServer::start().await;
    let body = TagCardRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/cards/7/taggings.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .tag(7, &body)
        .await
        .unwrap();
    server.verify().await;
}

/// `TriageCard`.
#[tokio::test]
async fn triage() {
    let server = MockServer::start().await;
    let body = TriageCardRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/cards/7/triage.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .triage(7, &body)
        .await
        .unwrap();
    server.verify().await;
}

/// `UnTriageCard`.
#[tokio::test]
async fn un_triage() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/triage.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .un_triage(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `UngoldCard`.
#[tokio::test]
async fn ungold() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/goldness.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .ungold(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `UnpinCard`.
#[tokio::test]
async fn unpin() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/pin.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .unpin(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `UnwatchCard`.
#[tokio::test]
async fn unwatch() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/watch.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .unwatch(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `UpdateCard`.
#[tokio::test]
async fn update() {
    let server = MockServer::start().await;
    let expected: Card = Default::default();
    let body = UpdateCardRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/cards/7"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .update(7, &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `WatchCard`.
#[tokio::test]
async fn watch() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/cards/7/watch.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .cards()
        .watch(7)
        .await
        .unwrap();
    server.verify().await;
}
