// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateColumn`.
#[tokio::test]
async fn create() {
    let server = MockServer::start().await;
    let expected: Column = Default::default();
    let body = CreateColumnRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/boards/x-board_id/columns.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .columns()
        .create("x-board_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeleteColumn`.
#[tokio::test]
async fn delete() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/boards/x-board_id/columns/x-column_id"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .columns()
        .delete("x-board_id", "x-column_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `GetColumn`.
#[tokio::test]
async fn get() {
    let server = MockServer::start().await;
    let expected: Column = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id/columns/x-column_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .columns()
        .get("x-board_id", "x-column_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListColumns`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Column> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id/columns.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .columns()
        .list("x-board_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `MoveColumnLeft`.
#[tokio::test]
async fn move_left() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/columns/x-column_id/left_position.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .columns()
        .move_left("x-column_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `MoveColumnRight`.
#[tokio::test]
async fn move_right() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/columns/x-column_id/right_position.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .columns()
        .move_right("x-column_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `UpdateColumn`.
#[tokio::test]
async fn update() {
    let server = MockServer::start().await;
    let expected: Column = Default::default();
    let body = UpdateColumnRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/boards/x-board_id/columns/x-column_id"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .columns()
        .update("x-board_id", "x-column_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}
