// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateComment`.
#[tokio::test]
async fn create() {
    let server = MockServer::start().await;
    let expected: Comment = Default::default();
    let body = CreateCommentRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/cards/7/comments.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .comments()
        .create(7, &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeleteComment`.
#[tokio::test]
async fn delete() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/comments/x-comment_id"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .comments()
        .delete(7, "x-comment_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `GetComment`.
#[tokio::test]
async fn get() {
    let server = MockServer::start().await;
    let expected: Comment = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/cards/7/comments/x-comment_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .comments()
        .get(7, "x-comment_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListComments`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Comment> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/cards/7/comments.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .comments()
        .list(7)
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `UpdateComment`.
#[tokio::test]
async fn update() {
    let server = MockServer::start().await;
    let expected: Comment = Default::default();
    let body = UpdateCommentRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/cards/7/comments/x-comment_id"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .comments()
        .update(7, "x-comment_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}
