// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `RegisterDevice`.
#[tokio::test]
async fn register() {
    let server = MockServer::start().await;
    let body = RegisterDeviceRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/devices"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .devices()
        .register(&body)
        .await
        .unwrap();
    server.verify().await;
}

/// `UnregisterDevice`.
#[tokio::test]
async fn unregister() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/devices/x-device_token"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .devices()
        .unregister("x-device_token")
        .await
        .unwrap();
    server.verify().await;
}
