// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `GetMyIdentity`.
#[tokio::test]
async fn get_my_identity() {
    let server = MockServer::start().await;
    let expected: Identity = Default::default();
    Mock::given(method("GET"))
        .and(path("/my/identity.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server).identity().get_my_identity().await.unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `UpdateMyTimezone`.
#[tokio::test]
async fn update_my_timezone() {
    let server = MockServer::start().await;
    let body = UpdateMyTimezoneRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/my/timezone.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .identity()
        .update_my_timezone(&body)
        .await
        .unwrap();
    server.verify().await;
}
