// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

#![cfg(feature = "reqwest")]
#![allow(clippy::pedantic, clippy::unwrap_used, missing_docs)]

mod access_tokens;
mod account;
mod boards;
mod cards;
mod columns;
mod comments;
mod devices;
mod identity;
mod notifications;
mod pins;
mod reactions;
mod search;
mod sessions;
mod steps;
mod tags;
mod uploads;
mod users;
mod webhooks;

use std::time::Duration;

use fizzy_sdk::{Client, Config};
use wiremock::MockServer;

/// A client pointed at the mock server, with retries wound down so a failing test
/// fails fast.
fn client(server: &MockServer) -> Client {
    Client::builder(Config::default().with_base_url(server.uri()))
        .access_token("test-token")
        .max_attempts(1)
        .max_jitter(Duration::ZERO)
        .build()
        .unwrap()
}
