// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use fizzy_sdk::services::notifications::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `BulkReadNotifications`.
#[tokio::test]
async fn bulk_read() {
    let server = MockServer::start().await;
    let body = BulkReadNotificationsRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/notifications/bulk_reading.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .notifications()
        .bulk_read(&body)
        .await
        .unwrap();
    server.verify().await;
}

/// `GetNotificationSettings`.
#[tokio::test]
async fn get_settings() {
    let server = MockServer::start().await;
    let expected: NotificationSettings = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/notifications/settings.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .notifications()
        .get_settings()
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `GetNotificationTray`.
#[tokio::test]
async fn get_tray() {
    let server = MockServer::start().await;
    let expected: Vec<Notification> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/notifications/tray.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .notifications()
        .get_tray(&GetNotificationTrayParams::default())
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListNotifications`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Notification> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/notifications.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .notifications()
        .list(&ListNotificationsParams::default())
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `ReadNotification`.
#[tokio::test]
async fn read() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/notifications/x-notification_id/reading.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .notifications()
        .read("x-notification_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `UnreadNotification`.
#[tokio::test]
async fn unread() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/notifications/x-notification_id/reading.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .notifications()
        .unread("x-notification_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `UpdateNotificationSettings`.
#[tokio::test]
async fn update_settings() {
    let server = MockServer::start().await;
    let body = UpdateNotificationSettingsRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/notifications/settings.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .notifications()
        .update_settings(&body)
        .await
        .unwrap();
    server.verify().await;
}
