// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `ListPins`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Card> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/my/pins.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .pins()
        .list()
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}
