// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateCardReaction`.
#[tokio::test]
async fn create_card() {
    let server = MockServer::start().await;
    let expected: Reaction = Default::default();
    let body = CreateCardReactionRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/cards/7/reactions.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .reactions()
        .create_card(7, &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `CreateCommentReaction`.
#[tokio::test]
async fn create_comment() {
    let server = MockServer::start().await;
    let expected: Reaction = Default::default();
    let body = CreateCommentReactionRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/cards/7/comments/x-comment_id/reactions.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .reactions()
        .create_comment(7, "x-comment_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeleteCardReaction`.
#[tokio::test]
async fn delete_card() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/reactions/x-reaction_id"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .reactions()
        .delete_card(7, "x-reaction_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `DeleteCommentReaction`.
#[tokio::test]
async fn delete_comment() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path(
            "/999/cards/7/comments/x-comment_id/reactions/x-reaction_id",
        ))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .reactions()
        .delete_comment(7, "x-comment_id", "x-reaction_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `ListCardReactions`.
#[tokio::test]
async fn list_card() {
    let server = MockServer::start().await;
    let expected: Vec<Reaction> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/cards/7/reactions.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .reactions()
        .list_card(7)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListCommentReactions`.
#[tokio::test]
async fn list_comment() {
    let server = MockServer::start().await;
    let expected: Vec<Reaction> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/cards/7/comments/x-comment_id/reactions.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .reactions()
        .list_comment(7, "x-comment_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}
