// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateStep`.
#[tokio::test]
async fn create() {
    let server = MockServer::start().await;
    let expected: Step = Default::default();
    let body = CreateStepRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/cards/7/steps.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .steps()
        .create(7, &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeleteStep`.
#[tokio::test]
async fn delete() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/cards/7/steps/x-step_id"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .steps()
        .delete(7, "x-step_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `GetStep`.
#[tokio::test]
async fn get() {
    let server = MockServer::start().await;
    let expected: Step = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/cards/7/steps/x-step_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .steps()
        .get(7, "x-step_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListSteps`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Step> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/cards/7/steps.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .steps()
        .list(7)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `UpdateStep`.
#[tokio::test]
async fn update() {
    let server = MockServer::start().await;
    let expected: Step = Default::default();
    let body = UpdateStepRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/cards/7/steps/x-step_id"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .steps()
        .update(7, "x-step_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}
