// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateDirectUpload`.
#[tokio::test]
async fn create_direct_upload() {
    let server = MockServer::start().await;
    let expected: DirectUpload = Default::default();
    let body = CreateDirectUploadRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/rails/active_storage/direct_uploads"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .uploads()
        .create_direct_upload(&body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}
