// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `ConfirmEmailAddressChange`.
#[tokio::test]
async fn confirm_email_address_change() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path(
            "/999/users/x-user_id/email_addresses/x-email_address_token/confirmation.json",
        ))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .confirm_email_address_change("x-user_id", "x-email_address_token")
        .await
        .unwrap();
    server.verify().await;
}

/// `CreatePushSubscription`.
#[tokio::test]
async fn create_push_subscription() {
    let server = MockServer::start().await;
    let body = CreatePushSubscriptionRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/users/x-user_id/push_subscriptions.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .create_push_subscription("x-user_id", &body)
        .await
        .unwrap();
    server.verify().await;
}

/// `CreateUserDataExport`.
#[tokio::test]
async fn create_user_data_export() {
    let server = MockServer::start().await;
    let expected: DataExport = Default::default();
    Mock::given(method("POST"))
        .and(path("/999/users/x-user_id/data_exports.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .create_user_data_export("x-user_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeactivateUser`.
#[tokio::test]
async fn deactivate() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/users/x-user_id"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .deactivate("x-user_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `DeleteUserAvatar`.
#[tokio::test]
async fn delete_avatar() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/users/x-user_id/avatar"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .delete_avatar("x-user_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `DeletePushSubscription`.
#[tokio::test]
async fn delete_push_subscription() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path(
            "/999/users/x-user_id/push_subscriptions/x-push_subscription_id",
        ))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .delete_push_subscription("x-user_id", "x-push_subscription_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `GetUser`.
#[tokio::test]
async fn get() {
    let server = MockServer::start().await;
    let expected: User = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/users/x-user_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .get("x-user_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `GetUserDataExport`.
#[tokio::test]
async fn get_user_data_export() {
    let server = MockServer::start().await;
    let expected: DataExport = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/users/x-user_id/data_exports/x-export_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .get_user_data_export("x-user_id", "x-export_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListUsers`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<User> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/users.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .list()
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `RequestEmailAddressChange`.
#[tokio::test]
async fn request_email_address_change() {
    let server = MockServer::start().await;
    let body = RequestEmailAddressChangeRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/users/x-user_id/email_addresses.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .request_email_address_change("x-user_id", &body)
        .await
        .unwrap();
    server.verify().await;
}

/// `UpdateUser`.
#[tokio::test]
async fn update() {
    let server = MockServer::start().await;
    let expected: User = Default::default();
    let body = UpdateUserRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/users/x-user_id"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .update("x-user_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `UpdateUserRole`.
#[tokio::test]
async fn update_role() {
    let server = MockServer::start().await;
    let body = UpdateUserRoleRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/users/x-user_id/role.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .users()
        .update_role("x-user_id", &body)
        .await
        .unwrap();
    server.verify().await;
}
