// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `ActivateWebhook`.
#[tokio::test]
async fn activate() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path(
            "/999/boards/x-board_id/webhooks/x-webhook_id/activation.json",
        ))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .webhooks()
        .activate("x-board_id", "x-webhook_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `CreateWebhook`.
#[tokio::test]
async fn create() {
    let server = MockServer::start().await;
    let expected: Webhook = Default::default();
    let body = CreateWebhookRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/999/boards/x-board_id/webhooks.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .webhooks()
        .create("x-board_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DeleteWebhook`.
#[tokio::test]
async fn delete() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/999/boards/x-board_id/webhooks/x-webhook_id"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .webhooks()
        .delete("x-board_id", "x-webhook_id")
        .await
        .unwrap();
    server.verify().await;
}

/// `GetWebhook`.
#[tokio::test]
async fn get() {
    let server = MockServer::start().await;
    let expected: Webhook = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id/webhooks/x-webhook_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .webhooks()
        .get("x-board_id", "x-webhook_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListWebhooks`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Webhook> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/boards/x-board_id/webhooks.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .webhooks()
        .list("x-board_id")
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListWebhookDeliveries`.
#[tokio::test]
async fn list_webhook_deliveries() {
    let server = MockServer::start().await;
    let expected: Vec<WebhookDelivery> = Default::default();
    Mock::given(method("GET"))
        .and(path(
            "/999/boards/x-board_id/webhooks/x-webhook_id/deliveries.json",
        ))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .webhooks()
        .list_webhook_deliveries("x-board_id", "x-webhook_id")
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}

/// `UpdateWebhook`.
#[tokio::test]
async fn update() {
    let server = MockServer::start().await;
    let expected: Webhook = Default::default();
    let body = UpdateWebhookRequestContent::default();
    Mock::given(method("PATCH"))
        .and(path("/999/boards/x-board_id/webhooks/x-webhook_id"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .webhooks()
        .update("x-board_id", "x-webhook_id", &body)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}
