// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

#![allow(clippy::pedantic, clippy::unwrap_used, missing_docs)]

mod sessions;
mod widgets;

use std::time::Duration;

use fizzy_sdk::{Client, Config};
use wiremock::MockServer;

/// A client pointed at the mock server, with retries wound down so a failing test
/// fails fast.
fn client(server: &MockServer) -> Client {
    Client::builder(Config::default().with_base_url(server.uri()))
        .access_token("test-token")
        .max_attempts(1)
        .max_jitter(Duration::ZERO)
        .build()
        .unwrap()
}
