// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use wiremock::matchers::{body_json, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CreateSession`.
#[tokio::test]
async fn create() {
    let server = MockServer::start().await;
    let expected: PendingAuthentication = Default::default();
    let body = CreateSessionRequestContent::default();
    Mock::given(method("POST"))
        .and(path("/session.json"))
        .and(body_json(serde_json::to_value(&body).unwrap()))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server).sessions().create(&body).await.unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `DestroySession`.
#[tokio::test]
async fn destroy() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path("/session.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server).sessions().destroy().await.unwrap();
    server.verify().await;
}
