// Generated by fizzy-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

use fizzy_sdk::models::*;
use fizzy_sdk::services::widgets::*;
use wiremock::matchers::{method, path, query_param};
use wiremock::{Mock, MockServer, ResponseTemplate};

use crate::client;

/// `CloseWidget`.
#[tokio::test]
async fn close() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/999/widgets/7/closure.json"))
        .respond_with(ResponseTemplate::new(204))
        .expect(1)
        .mount(&server)
        .await;
    client(&server)
        .for_account("999")
        .unwrap()
        .widgets()
        .close(7)
        .await
        .unwrap();
    server.verify().await;
}

/// `GetWidget`.
#[tokio::test]
async fn get() {
    let server = MockServer::start().await;
    let expected: Widget = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/widgets/7"))
        .and(query_param("expand", "true"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .widgets()
        .get(7, true)
        .await
        .unwrap();
    assert_eq!(answer, expected);
    server.verify().await;
}

/// `ListWidgets`.
#[tokio::test]
async fn list() {
    let server = MockServer::start().await;
    let expected: Vec<Widget> = Default::default();
    Mock::given(method("GET"))
        .and(path("/999/widgets.json"))
        .respond_with(
            ResponseTemplate::new(200).set_body_json(serde_json::to_value(&expected).unwrap()),
        )
        .expect(1)
        .mount(&server)
        .await;
    let answer = client(&server)
        .for_account("999")
        .unwrap()
        .widgets()
        .list(&ListWidgetsParams::default())
        .await
        .unwrap();
    assert_eq!(answer.value(), &expected);
    assert!(!answer.has_next());
    server.verify().await;
}
